title: OOD Time Series

logo: "/assets/img/logo-llmeval.png"
favicon_ico: "/assets/img/logo.png"

remote_theme: just-the-docs/just-the-docs
search_enabled: true
search_tokenizer_separator: /[\s/]+/
heading_anchors: true
color_scheme: "light"

# nav_external_links:
#   - title: LLM enhancement
#     url: https://llm-enhance.github.io

footer_content: "Contact us <a href=\"http://jd92.wang\">here</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

ga_tracking_anonymize_ip: true
